export const IMAGE_LIST_REQUEST = 'IMAGE_LIST_REQUEST'
export const IMAGE_LIST_SUCCESS = 'IMAGE_LIST_SUCCESS'
export const IMAGE_LIST_FAIL = 'IMAGE_LIST_FAIL'


export const IMAGE_CREATE_REQUEST = 'IMAGE_CREATE_REQUEST'
export const IMAGE_CREATE_SUCCESS = 'IMAGE_CREATE_SUCCESS'
export const IMAGE_CREATE_FAIL = 'IMAGE_CREATE_FAIL'


export const IMAGE_DELETE_REQUEST = 'IMAGE_DELETE_REQUEST'
export const IMAGE_DELETE_SUCCESS = 'IMAGE_DELETE_SUCCESS'
export const IMAGE_DELETE_FAIL = 'IMAGE_DELETE_FAIL'