const products = [
  {
    _id: '1',
    name: 'name 1',
    images: '/images/name.jpg',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur magni animi, blanditiis harum pariatur architecto numquam error. Quisquam, impedit amet quae, rem beatae iure fugit provident esse sint eos ad!',
    brand: 'brand A',
    category: 'Electornics',
    image: '/images/item1.png',
    offer: 10,
    price: 98,
    countInStock: 5,
    rating: 4.5,
    numOfReviews: 4,
  },
  {
    _id: '2',
    name: 'name 2',
    images: '/images/name.jpg',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur magni animi, blanditiis harum pariatur architecto numquam error. Quisquam, impedit amet quae, rem beatae iure fugit provident esse sint eos ad!',
    brand: 'brand B',
    category: 'Electornics',
    image: '/images/item1.png',
    offer: 10,
    price: 90,
    countInStock: 6,
    rating: 4.3,
    numOfReviews: 3,
  },
  {
    _id: '3',
    name: 'name 3',
    images: '/images/name.jpg',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur magni animi, blanditiis harum pariatur architecto numquam error. Quisquam, impedit amet quae, rem beatae iure fugit provident esse sint eos ad!',
    brand: 'brand C',
    category: 'Another',
    image: '/images/item1.png',
    offer: 10,
    price: 93,
    countInStock: 10,
    rating: 4.5,
    numOfReviews: 5,
  },
  {
    _id: '4',
    name: 'name 4',
    images: '/images/name.jpg',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur magni animi, blanditiis harum pariatur architecto numquam error. Quisquam, impedit amet quae, rem beatae iure fugit provident esse sint eos ad!',
    brand: 'brand A',
    category: 'Another',
    image: '/images/item1.png',
    offer: 10,
    price: 80,
    countInStock: 6,
    rating: 4.5,
    numOfReviews: 10,
  },
  {
    _id: '5',
    name: 'name 5',
    images: '/images/name.jpg',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur magni animi, blanditiis harum pariatur architecto numquam error. Quisquam, impedit amet quae, rem beatae iure fugit provident esse sint eos ad!',
    brand: 'brand A',
    category: 'Electornics',
    image: '/images/item1.png',
    offer: 10,
    price: 83,
    countInStock: 5,
    rating: 4.5,
    numOfReviews: 7,
  },
]

export default products
